#!/bin/sh

# Ensure directory to store results is there
mkdir results -p

# ALL OPERATIONS
timeout 30m ../build/evaluator --runs=2 --output=results/times_1d.txt --index_structures=sequential_scan,1 --index_structures=octree,1,0,1 --index_structures=pyramid_tree,1,0,1 -t../test_data/operation_lists/randuniform_1d.ops -t../test_data/operation_lists/skewed_1d.ops -t../test_data/operation_lists/randuniform_1d.ops --index_structures=pyramid_tree,1,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_2d.txt --index_structures=sequential_scan,2 --index_structures=octree,2,0,1 --index_structures=pyramid_tree,2,0,1 -t../test_data/operation_lists/randuniform_2d.ops -t../test_data/operation_lists/skewed_2d.ops -t../test_data/operation_lists/randuniform_2d.ops --index_structures=pyramid_tree,2,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_3d.txt --index_structures=sequential_scan,3 --index_structures=octree,3,0,1 --index_structures=pyramid_tree,3,0,1 -t../test_data/operation_lists/randuniform_3d.ops -t../test_data/operation_lists/skewed_3d.ops -t../test_data/operation_lists/randuniform_3d.ops --index_structures=pyramid_tree,3,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_5d.txt --index_structures=sequential_scan,5 --index_structures=octree,5,0,1 --index_structures=pyramid_tree,5,0,1 -t../test_data/operation_lists/randuniform_5d.ops -t../test_data/operation_lists/skewed_5d.ops -t../test_data/operation_lists/randuniform_5d.ops --index_structures=pyramid_tree,5,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_8d.txt --index_structures=sequential_scan,8 --index_structures=octree,8,0,1 --index_structures=pyramid_tree,8,0,1 -t../test_data/operation_lists/randuniform_8d.ops -t../test_data/operation_lists/skewed_8d.ops -t../test_data/operation_lists/randuniform_8d.ops --index_structures=pyramid_tree,8,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_10d.txt --index_structures=sequential_scan,10 --index_structures=octree,10,0,1 --index_structures=pyramid_tree,10,0,1 -t../test_data/operation_lists/randuniform_10d.ops -t../test_data/operation_lists/skewed_10d.ops -t../test_data/operation_lists/randuniform_10d.ops --index_structures=pyramid_tree,10,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_30d.txt --index_structures=sequential_scan,30 --index_structures=octree,30,0,1 --index_structures=pyramid_tree,30,0,1 -t../test_data/operation_lists/randuniform_30d.ops -t../test_data/operation_lists/skewed_30d.ops -t../test_data/operation_lists/randuniform_30d.ops --index_structures=pyramid_tree,30,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_50d.txt --index_structures=sequential_scan,50 --index_structures=octree,50,0,1 --index_structures=pyramid_tree,50,0,1 -t../test_data/operation_lists/randuniform_50d.ops -t../test_data/operation_lists/skewed_50d.ops -t../test_data/operation_lists/randuniform_50d.ops --index_structures=pyramid_tree,50,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_100d.txt --index_structures=sequential_scan,100 --index_structures=octree,100,0,1 --index_structures=pyramid_tree,100,0,1 -t../test_data/operation_lists/randuniform_100d.ops -t../test_data/operation_lists/skewed_100d.ops -t../test_data/operation_lists/randuniform_100d.ops --index_structures=pyramid_tree,100,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_200d.txt --index_structures=sequential_scan,200 --index_structures=octree,200,0,1 --index_structures=pyramid_tree,200,0,1 -t../test_data/operation_lists/randuniform_200d.ops -t../test_data/operation_lists/skewed_200d.ops -t../test_data/operation_lists/randuniform_200d.ops --index_structures=pyramid_tree,200,0,1,6000

# RANDOM OPERATIONS
timeout 30m ../build/evaluator --runs=2 --output=results/times_1d_random.txt --index_structures=sequential_scan,1 --index_structures=octree,1,0,1 --index_structures=pyramid_tree,1,0,1 -t../test_data/operation_lists/randuniform_1d_random.ops -t../test_data/operation_lists/skewed_1d_random.ops -t../test_data/operation_lists/randuniform_1d_random.ops --index_structures=pyramid_tree,1,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_2d_random.txt --index_structures=sequential_scan,2 --index_structures=octree,2,0,1 --index_structures=pyramid_tree,2,0,1 -t../test_data/operation_lists/randuniform_2d_random.ops -t../test_data/operation_lists/skewed_2d_random.ops -t../test_data/operation_lists/randuniform_2d_random.ops --index_structures=pyramid_tree,2,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_3d_random.txt --index_structures=sequential_scan,3 --index_structures=octree,3,0,1 --index_structures=pyramid_tree,3,0,1 -t../test_data/operation_lists/randuniform_3d_random.ops -t../test_data/operation_lists/skewed_3d_random.ops -t../test_data/operation_lists/randuniform_3d_random.ops --index_structures=pyramid_tree,3,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_5d_random.txt --index_structures=sequential_scan,5 --index_structures=octree,5,0,1 --index_structures=pyramid_tree,5,0,1 -t../test_data/operation_lists/randuniform_5d_random.ops -t../test_data/operation_lists/skewed_5d_random.ops -t../test_data/operation_lists/randuniform_5d_random.ops --index_structures=pyramid_tree,5,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_8d_random.txt --index_structures=sequential_scan,8 --index_structures=octree,8,0,1 --index_structures=pyramid_tree,8,0,1 -t../test_data/operation_lists/randuniform_8d_random.ops -t../test_data/operation_lists/skewed_8d_random.ops -t../test_data/operation_lists/randuniform_8d_random.ops --index_structures=pyramid_tree,8,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_10d_random.txt --index_structures=sequential_scan,10 --index_structures=octree,10,0,1 --index_structures=pyramid_tree,10,0,1 -t../test_data/operation_lists/randuniform_10d_random.ops -t../test_data/operation_lists/skewed_10d_random.ops -t../test_data/operation_lists/randuniform_10d_random.ops --index_structures=pyramid_tree,10,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_30d_random.txt --index_structures=sequential_scan,30 --index_structures=octree,30,0,1 --index_structures=pyramid_tree,30,0,1 -t../test_data/operation_lists/randuniform_30d_random.ops -t../test_data/operation_lists/skewed_30d_random.ops -t../test_data/operation_lists/randuniform_30d_random.ops --index_structures=pyramid_tree,30,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_50d_random.txt --index_structures=sequential_scan,50 --index_structures=octree,50,0,1 --index_structures=pyramid_tree,50,0,1 -t../test_data/operation_lists/randuniform_50d_random.ops -t../test_data/operation_lists/skewed_50d_random.ops -t../test_data/operation_lists/randuniform_50d_random.ops --index_structures=pyramid_tree,50,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_100d_random.txt --index_structures=sequential_scan,100 --index_structures=octree,100,0,1 --index_structures=pyramid_tree,100,0,1 -t../test_data/operation_lists/randuniform_100d_random.ops -t../test_data/operation_lists/skewed_100d_random.ops -t../test_data/operation_lists/randuniform_100d_random.ops --index_structures=pyramid_tree,100,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_200d_random.txt --index_structures=sequential_scan,200 --index_structures=octree,200,0,1 --index_structures=pyramid_tree,200,0,1 -t../test_data/operation_lists/randuniform_200d_random.ops -t../test_data/operation_lists/skewed_200d_random.ops -t../test_data/operation_lists/randuniform_200d_random.ops --index_structures=pyramid_tree,200,0,1,6000

# ASTROPHYSICS DATASET (ALL AND RANDOM)
timeout 30m ../build/evaluator --runs=2 --output=results/times_astrophysics.txt --index_structures=sequential_scan,10 --index_structures=octree,10,0,1 --index_structures=pyramid_tree,10,0,1 -t../test_data/operation_lists/multifield.0099_75x31x31.ops --index_structures=pyramid_tree,10,0,1,6000
timeout 30m ../build/evaluator --runs=2 --output=results/times_astrophysics_random.txt --index_structures=sequential_scan,10 --index_structures=octree,10,0,1 --index_structures=pyramid_tree,10,0,1 -t../test_data/operation_lists/multifield.0099_75x31x31_random.ops --index_structures=pyramid_tree,10,0,1,6000